### ISSUE TITLE
[Feature Request] formatting in markdown

### ISSUE THREAD

**Issue by Vingolf** [hedgieinsocks/nine-notes#1]
Hi  @hedgieinsocks,

to have some features to format notes in markdown or [wikitext](https://tiddlywiki.com/static/Formatting%2520in%2520WikiText.html) would be nice.

**Comment by hedgieinsocks** [comment]
Sorry for the late reply, but I guess better later than never. Unfortunately, this will require quite a lot of coding beyond my poor js knowledge. And considering that I'm no longer a Firefox user, this project might get only some critical fixes in the future.
